version: '3'
services:
  lightserver:
  image: light-server:latest  # 使用最新版本的 Redis 镜像
  container_name: lightService
  mem_limit: 256m
  restart: always
  ports:
    - "3000:3000"  # 将主机的 3000 端口映射到容器的 3000 端口